import { FormEvent, useState } from "react";
import { useLocation } from "wouter";
import { Database, Search, UserRoundSearch } from "lucide-react";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { resolveBlockballPlayer } from "@/lib/blockball-api";

export function BlockballPlayers() {
  const [value, setValue] = useState("");
  const [error, setError] = useState("");
  const [, navigate] = useLocation();

  async function submit(event: FormEvent) {
    event.preventDefault();
    setError("");
    const search = value.trim();
    if (!search) return;
    if (/^[0-9a-f-]{36}$/i.test(search)) return navigate(`/blockball/profile/${search.toLowerCase()}`);
    try {
      const player = await resolveBlockballPlayer(search);
      navigate(`/blockball/profile/${player.uuid}`);
    } catch {
      setError("No player with that username was found in the BlockBall database.");
    }
  }

  return (
    <div className="container mx-auto max-w-4xl px-4 py-14">
      <section className="relative overflow-hidden rounded-[28px] border border-sky-400/20 bg-gradient-to-br from-sky-400/12 via-white/[0.035] to-transparent p-8 text-center md:p-14">
        <div className="absolute left-1/2 top-0 h-48 w-96 -translate-x-1/2 rounded-full bg-sky-400/10 blur-3xl" />
        <UserRoundSearch className="relative mx-auto h-12 w-12 text-sky-400" />
        <p className="relative mt-5 font-display text-xs font-semibold uppercase tracking-[0.3em] text-sky-400">NEXT BlockBall Database</p>
        <h1 className="relative mt-3 font-display text-4xl font-bold uppercase md:text-6xl">Player Search</h1>
        <p className="relative mx-auto mt-4 max-w-xl text-muted-foreground">Find a profile using the exact in-game username or the offline-mode UUID generated by the server.</p>
        <form onSubmit={submit} className="relative mx-auto mt-8 flex max-w-2xl flex-col gap-3 sm:flex-row">
          <Input value={value} onChange={(event) => setValue(event.target.value)} placeholder="Username or offline UUID" className="h-12 bg-black/20" />
          <Button className="h-12 px-7"><Search className="mr-2 h-4 w-4" />Search</Button>
        </form>
        {error && <p className="relative mt-4 text-sm text-destructive">{error}</p>}
        <div className="relative mx-auto mt-7 flex max-w-xl items-start gap-3 rounded-2xl border border-white/8 bg-black/15 p-4 text-left text-sm text-muted-foreground"><Database className="mt-0.5 h-5 w-5 shrink-0 text-sky-400" /><p>BlockBall runs in offline mode. Player identity is resolved exclusively through the server database and does not depend on Mojang services.</p></div>
      </section>
    </div>
  );
}
